default_stages: [commit]

repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: system
        types: [rust]

  - repo: local
    hooks:
      - id: rustclippy
        name: rustclippy
        entry: cargo clippy --all-targets --all-features -- -Dclippy::all
        pass_filenames: false
        language: system
        types: [rust]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [commit]
