[package]
name = "image-converter-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"

[lib]
crate-type = ["cdylib", "rlib"]
